model:
    name: iris-classification
    description: "Iris classification model with multiple implementations (sklearn and PyTorch)"
    tags:
        - classification
        - sklearn
        - pytorch
    license: MIT

enable_cache: False
